### ISSUE TITLE
Tebrikler

### ISSUE THREAD

**Issue by eersoy93** [elera714/elerais#1]
Merhabalar,

ELERA İS'i yaptığınız için tebrik ederim.

İyi çalışmalar.

**Comment by elera714** [comment]
Merhaba, @eersoy93 

Teşekkür ederim, sağolun.

Sıradışı bir çalışma modeli olan, "İşletim Sistemi" projeleriniz için ben de sizi tebrik eder, çalışmalarınızda başarılar dilerim.
